server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Xử lý React Router không bị 404 khi f5 trang
        try_files $uri $uri/ /index.html;
    }

    # Proxy tự động các request /api sang container mock-api
    location /api/ {
        proxy_pass http://mock-api:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}